@startuml UseCase_EcoOil
left to right direction
skinparam packageStyle rectangle

actor "User (Rumah Tangga)" as user
actor "Mitra Kolektor (Driver)" as driver
actor "Admin Sistem" as admin

rectangle "Sistem Manajemen Jelantah (EcoOil)" {
    
    ' User Cases
    usecase "Login / Register" as UC1
    usecase "Request Penjemputan" as UC2
    usecase "Lihat Riwayat Transaksi" as UC3
    usecase "Tarik Saldo (Withdraw)" as UC4
    
    ' Driver Cases
    usecase "Terima Order Jemput" as UC5
    usecase "Input Timbangan & Verifikasi" as UC6
    usecase "Selesaikan Pengantaran" as UC7
    
    ' Admin Cases
    usecase "Validasi Penarikan Dana" as UC10
    usecase "Kelola User & Mitra" as UC11
    usecase "Atur Harga Beli" as UC12
}

' Relasi User
user --> UC1
user --> UC2
user --> UC3
user --> UC4

' Relasi Driver
driver --> UC1
driver --> UC5
driver --> UC6
driver --> UC7

' Relasi Admin
admin --> UC10
admin --> UC11
admin --> UC12

@enduml